name: Jenkins single-shot master

on:
  push:
    branches:
      - main  # Adjust based on your default branch

jobs:
  jenkinsfile-runner-prepackaged:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Use v2 for more stability

      - name: Run Jenkins Pipeline
        uses: jenkinsci/jenkinsfile-runner-github-actions/jenkinsfile-runner-prepackaged@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
