name: Jenkins Master Pipeline

on:
  push:
    branches:
      - master

jobs:
  jenkinsfile-runner-prepackaged:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Jenkins Pipeline
        uses: jenkinsci/jenkinsfile-runner-github-actions/jenkinsfile-runner-prepackaged@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_JENKINSFILE: 'Jenkinsfile'
          INPUT_PLUGINSTXT: 'plugins.txt'
          INPUT_COMMAND: 'run'
